### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by jacobdf** [joelcollinsdc/dragonboat-sorter#1]
Hi Joe
I like the description of this project. Are you still working on it? 
I coach several dragon boat teams in New Zealand so would love to see a more efficient way of handling the issues you are addressing.
I can't help with the coding, but may be able to assist with determining parameters, testing, or suggesting other requirements.
Cheers
Jacob

**Comment by joelcollinsdc** [comment]
Haha oh man yea this is a project I never really got time to make work.  There are 2 alternatives I know of, there is one app for iphones that does something similar to this, and the other my friend made a website that supposedly does things like help teams with sorting along with live results postings etc.  I can't find the URL of the latter, I need to look that up...

**Comment by joelcollinsdc** [comment]
Found it.. it says "under development", so you are probably a beta tester...

http://grunsports.com/lineup.cfm

**Comment by jacobdf** [comment]
Thanks Joel.
Your friend's calculator is very similar to what I do on a spreadsheet, but
his looks cleaner and I like the tilting graphics ;-).

I did a quick "beta test", all seems to work OK, except for
drum/drummer/steerer calcs, the ft-lbs calculated for those position appear
to be 10x higher.

Cheers

Jacob

**Comment by jacobdf** [comment]
Hi Joel

I checked the calculations in http://grunsports.com/lineup.cfm and I think
that for the drummer and steerer your friend used the distance of the nose
& stern to the center of bouyancy rather than their actual position.
Easy to fix

Regards

Jacob
